class Commands:
    LEECH = "leech@tormeet_bot"
    PURGE = "purge@tormeet_bot"
    PAUSEALL = "pauseall@tormeet_bot"
    RESUMEALL = "resumeall@tormeet_bot"
    STATUS = "status@tormeet_bot"
    SETTINGS = "settings@tormeet_bot"
    EXEC = "exec@tormeet_bot"
    UPLOAD = "upload@tormeet_bot"
    YTDL = "ytdl@tormeet_bot"
    PYTDL = "pytdl@tormeet_bot"
    ABOUT = "about@tormeet_bot"
    GETLOGS = "getlogs@tormeet_bot"
    SERVER = "server@tormeet_bot"
    USERSETTINGS = "usetting@tormeet_bot"
    INSTADL = "instadl@tormeet_bot"
    START = "start@tormeet_bot"
    USTATUS = "ustatus@tormeet_bot"
